name: Android Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cargar el código fuente
      uses: actions/checkout@v4

    - name: Configurar Java 17 con GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'

    - name: Configurar el Android SDK
      uses: android-actions/setup-android@v3

    - name: Compilar Clases de la Ticketera
      run: |
        mvn clean compile

    - name: Generar Paquete de Distribución Android
      run: |
        mvn gluonfx:compile gluonfx:package -Dgluonfx.target=android

    - name: Subir APK de Ticketmaster Generado
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: app-ticketmaster-android
        path: |
          target/gluonfx/android/*.apk
          target/*.jar
