name: Android Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cargar el código fuente
      uses: actions/checkout@v3

    - name: Configurar Java 17 con GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'

    - name: Configurar el Android SDK
      uses: android-actions/setup-android@v2

    - name: Compilar y Empaquetar APK con GluonFX
      run: |
        mvn gluonfx:compile gluonfx:package

    - name: Subir el APK generado como Artefacto
      uses: actions/upload-artifact@v3
      with:
        name: app-ticketmaster-android
        path: target/gluonfx/android/*.apk
